url: https://faunamanabi.github.io/
baseurl: 

# Site settings
title: Fauna of Manabi
email: dlizcano@yahoo.com
description: "Project: Caracterización ecológica de la fauna mediana y grande en áreas protegidas de la provincia de Manabí, Ecuador. Refugio de Vida Silvestre, Marino y Costero Pacoche. Parque Nacional Machalilla."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Diego J. Lizcano
  pic: 4
  position: Project Leader
  social:
    - title: github
      url: https://github.com/dlizcano
    - title: twitter
      url: https://twitter.com/dlizcano
    - title: facebook
      url: https://www.facebook.com/djlizcano
    - title: envelope
      url: mailto:dj.lizcano@gmail.com

- name: Pablo Ramírez Barajas
  pic: 5
  position: Project Leader
  social:
    - title: dribbble
      url: https://www.researchgate.net/profile/Pablo_Ramirez-Barajas
    - title: facebook
      url: https://www.facebook.com/pablo.ramirezbarajas
    - title: envelope
      url: mailto:pjrbarajas@gmail.com

- name: Laura Cervera
  pic: 6
  position: Researcher, Ecologist
  social:
    - title: envelope
      url: mailto:laura.cervera24@gmail.com
    - title: facebook
      url: https://www.facebook.com/morsa.intensa
    - title: dribbble
      url: http://www.aem.mamiferosdelecuador.com/miembros/lista/172-cervera-laura.html

- name: Violeta Pares
  pic: 9
  position: Researcher, Botanist
  social:
    - title: linkedin
      url: https://www.linkedin.com/pub/violeta-par%C3%A9s-jim%C3%A9nez/86/92/60a/en
    - title: envelope
      url: mailto:violeta.pares@uleam.edu.ec

- name: Sueanny Espinoza
  pic: 8
  position: Data assistant
  social:
    - title: envelope
      url: mailto:su_any13@hotmail.com
    - title: facebook
      url: https://www.facebook.com/
    - title: google-plus
      url: https://plus.google.com/u/0/118076742957644910177/about

- name: Diana Poaquiza
  pic: 7
  position: Data assistant
  social:
    - title: envelope
      url: mailto:acpoaquiza@gmail.com
    - title: facebook
      url: https://www.facebook.com/
    - title: google-plus
      url: https://plus.google.com/u/0/102476575988784604118/about

- name: Ernesto Merchán
  pic: 10
  position: Field assistant
  social:
    - title: envelope
      url: 
	  
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/faunamanabi
  - title: facebook
    url:
  - title: flickr
    url: http://www.flickr.com
  - title: dribbble 
    url: https://www.inaturalist.org/projects/fauna-de-manabi
  - title: github
    url: https://github.com/faunamanabi

# Postal address (add as many lines as necessary)
address:
  - line: Departamento Central de Investigación
  - line: Universidad Laica Eloy Alfaro de Manabí
  - line: Manta, Ecuador.

# Build settings
markdown: kramdown
permalink: pretty